// src/lib/auth/auth-types.js

// User related types
export const UserRole = {
  USER: 'USER',
  PREMIUM: 'PREMIUM',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN'
};

export const UserStatus = {
  ACTIVE: 'ACTIVE',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  SUSPENDED: 'SUSPENDED',
  DEACTIVATED: 'DEACTIVATED'
};

// Authentication providers
export const AuthProvider = {
  EMAIL: 'EMAIL',
  GOOGLE: 'GOOGLE',
  LINKEDIN: 'LINKEDIN',
  APPLE: 'APPLE',
  MICROSOFT: 'MICROSOFT'
};

// Multi-factor authentication methods
export const MFAMethod = {
  SMS: 'SMS',
  TOTP: 'TOTP',
  EMAIL: 'EMAIL',
  BACKUP_CODES: 'BACKUP_CODES'
};

// Citizenship status
export const CitizenshipStatus = {
  CITIZEN: 'CITIZEN',
  OCI: 'OCI',
  PIO: 'PIO'
};

// Income ranges
export const IncomeRange = {
  UNDER_50K: 'UNDER_50K',
  RANGE_50K_100K: '50K_100K',
  RANGE_100K_250K: '100K_250K',
  RANGE_250K_500K: '250K_500K',
  RANGE_500K_1M: '500K_1M',
  OVER_1M: 'OVER_1M'
};

// Investment experience levels
export const ExperienceLevel = {
  BEGINNER: 'BEGINNER',
  INTERMEDIATE: 'INTERMEDIATE',
  ADVANCED: 'ADVANCED',
  EXPERT: 'EXPERT'
};

// Risk tolerance levels
export const RiskTolerance = {
  CONSERVATIVE: 'CONSERVATIVE',
  MODERATE: 'MODERATE',
  AGGRESSIVE: 'AGGRESSIVE',
  VERY_AGGRESSIVE: 'VERY_AGGRESSIVE'
};

// Financial goals
export const FinancialGoal = {
  WEALTH_ACCUMULATION: 'WEALTH_ACCUMULATION',
  RETIREMENT_PLANNING: 'RETIREMENT_PLANNING',
  EDUCATION_FUNDING: 'EDUCATION_FUNDING',
  HOME_PURCHASE: 'HOME_PURCHASE',
  TAX_OPTIMIZATION: 'TAX_OPTIMIZATION',
  EMERGENCY_FUND: 'EMERGENCY_FUND'
};

// Portfolio sizes
export const PortfolioSize = {
  UNDER_10K: 'UNDER_10K',
  RANGE_10K_50K: '10K_50K',
  RANGE_50K_100K: '50K_100K',
  RANGE_100K_500K: '100K_500K',
  RANGE_500K_1M: '500K_1M',
  OVER_1M: 'OVER_1M'
};

// Investment types
export const InvestmentType = {
  STOCKS: 'STOCKS',
  BONDS: 'BONDS',
  MUTUAL_FUNDS: 'MUTUAL_FUNDS',
  ETF: 'ETF',
  REAL_ESTATE: 'REAL_ESTATE',
  COMMODITIES: 'COMMODITIES',
  CRYPTO: 'CRYPTO',
  FIXED_DEPOSITS: 'FIXED_DEPOSITS'
};

// Authentication error codes
export const AuthErrorCode = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  MFA_REQUIRED: 'MFA_REQUIRED',
  MFA_INVALID: 'MFA_INVALID',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  RATE_LIMITED: 'RATE_LIMITED',
  DEVICE_NOT_TRUSTED: 'DEVICE_NOT_TRUSTED',
  ONBOARDING_INCOMPLETE: 'ONBOARDING_INCOMPLETE',
  KYC_REQUIRED: 'KYC_REQUIRED',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR'
};

// Security event types
export const SecurityEventType = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  MFA_ENABLED: 'MFA_ENABLED',
  MFA_DISABLED: 'MFA_DISABLED',
  SUSPICIOUS_LOGIN: 'SUSPICIOUS_LOGIN',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  EMAIL_CHANGED: 'EMAIL_CHANGED',
  PROFILE_UPDATED: 'PROFILE_UPDATED'
};